# Generated by Django 4.1.13 on 2024-05-17 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="manager",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("addressline1", models.CharField(max_length=50, null=True)),
                ("addressline2", models.CharField(max_length=50, null=True)),
                ("city", models.CharField(max_length=50)),
                ("country", models.CharField(default="MA", max_length=5)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="owner",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("nationalid", models.CharField(max_length=50, null=True)),
                ("passportnumber", models.CharField(max_length=50, null=True)),
                ("addressline1", models.CharField(max_length=200, null=True)),
                ("addressline2", models.CharField(max_length=200, null=True)),
                ("city", models.CharField(max_length=50)),
                ("country", models.CharField(default="MA", max_length=5)),
                ("active", models.BooleanField(default=True)),
                (
                    "managerid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="owner.manager",
                    ),
                ),
            ],
        ),
    ]
